### ISSUE TITLE
Using ParallelExecutor results in unexpected test failure

### ISSUE THREAD

**Issue by upthewaterspout** [upthewaterspout/fates#9]
There is an ignored test in the repository, `shouldFailOnUnsynchronizedUpdate`, which is trying to use the `ParallelExecutor` utility to write a more concise test.

This test is currently failing with the below error. It looks like possibly the logic to not perform any scheduling actions during classloading (see `AtomicClassLoader`) is not working, because we are trying to interact with the scheduler during the loading of a class here.

```
java.lang.AssertionError: 
Expected: an instance of java.lang.AssertionError
     but: <java.lang.IllegalStateException: Hit error during testing> is a java.lang.IllegalStateException
Stacktrace was: java.lang.IllegalStateException: Hit error during testing
	at com.github.upthewaterspout.fates.core.threading.harness.ErrorCapturingExplorer.done(ErrorCapturingExplorer.java:46)
	at com.github.upthewaterspout.fates.core.states.StateExplorationHarness.explore(StateExplorationHarness.java:54)
	at com.github.upthewaterspout.fates.core.threading.Fates.run(Fates.java:57)
	at com.github.upthewaterspout.fates.integrationtest.UnsynchronizedUpdateTest.shouldFailOnUnsynchronizedUpdate(UnsynchronizedUpdateTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalStateException: System was not presented with the same options on the second run. Prevous choices: [Thread-2[ThreadID[0,0,], main[ThreadID[0,]], new choices [main[ThreadID[0,]]
	at com.github.upthewaterspout.fates.core.states.tree.DecisionTree.validateOptions(DecisionTree.java:138)
	at com.github.upthewaterspout.fates.core.states.tree.DecisionTree.setOptions(DecisionTree.java:68)
	at com.github.upthewaterspout.fates.core.states.depthfirst.DepthFirstExplorer.decide(DepthFirstExplorer.java:40)
	at com.github.upthewaterspout.fates.core.threading.harness.ErrorCapturingExplorer.decide(ErrorCapturingExplorer.java:73)
	at com.github.upthewaterspout.fates.core.threading.scheduler.SchedulerState.getNextThread(SchedulerState.java:152)
	at com.github.upthewaterspout.fates.core.threading.scheduler.SchedulerState.chooseNextThread(SchedulerState.java:89)
	at com.github.upthewaterspout.fates.core.threading.scheduler.ThreadSchedulingListener.yield(ThreadSchedulingListener.java:146)
	at com.github.upthewaterspout.fates.core.threading.scheduler.ThreadSchedulingListener.beforeGetField(ThreadSchedulingListener.java:129)
	at com.github.upthewaterspout.fates.core.threading.harness.ExecutionEventListenerWithAtomicControl.beforeGetField(ExecutionEventListenerWithAtomicControl.java:139)
	at com.github.upthewaterspout.fates.core.threading.harness.ThreadLocalEventListener.beforeGetField(ThreadLocalEventListener.java:54)
	at com.github.upthewaterspout.fates.core.threading.instrument.NonReentrantExecutionEventListener.beforeGetField(NonReentrantExecutionEventListener.java:59)
	at com.github.upthewaterspout.fates.core.threading.instrument.ExecutionEventSingleton.beforeGetField(ExecutionEventSingleton.java:65)
	at java.util.zip.ZipCoder.encoder(ZipCoder.java:157)
	at java.util.zip.ZipCoder.getBytes(ZipCoder.java:77)
	at java.util.zip.ZipFile.getEntry(ZipFile.java:316)
	at java.util.jar.JarFile.getEntry(JarFile.java:240)
	at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1042)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:239)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:365)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.github.upthewaterspout.fates.integrationtest.UnsynchronizedUpdateTest$UnsynchronizedUpdate.<init>(UnsynchronizedUpdateTest.java:68)
	at com.github.upthewaterspout.fates.integrationtest.UnsynchronizedUpdateTest.lambda$shouldFailOnUnsynchronizedUpdate$0(UnsynchronizedUpdateTest.java:41)
	at com.github.upthewaterspout.fates.core.threading.Fates.lambda$instrumentTest$0(Fates.java:73)
	at com.github.upthewaterspout.fates.core.states.StateExplorationHarness.explore(StateExplorationHarness.java:53)
	... 26 more
```

**Comment by upthewaterspout** [comment]
This was fixed by bdd20043
